import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { DialogueStoreProvider } from "~/providers/dialogue-store-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="ru"
      className={`${GeistSans.variable} dark bg-background text-foreground`}
    >
      <DialogueStoreProvider>
        <body className="flex justify-center">
          <main className="flex h-screen w-full max-w-xl bg-accent">
            {children}
          </main>
        </body>
      </DialogueStoreProvider>
    </html>
  );
}
