import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { type Metadata } from "next";
import { DialogueStoreProvider } from "~/providers/dialogue-store-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const font = Inter({ subsets: ["latin", "cyrillic", "cyrillic-ext"] });

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="ru"
      className={`${font.className} dark bg-background text-foreground`}
    >
      <DialogueStoreProvider>
        <body className="flex h-screen justify-center">
          <main className="flex w-full max-w-xl bg-accent">{children}</main>
        </body>
      </DialogueStoreProvider>
    </html>
  );
}
